const express=require("express");
const router=express.Router();
const protect=require("../middilware/authMiddleware");
const upload=require("../middilware/uploadMiddleware");
const {addvehicle,getvehicle,getvehiclebyid,deletevehiclebyid,updatevehiclebyid,searchAvailableVehicles}=require("../controllers/vehicleController");
const admin = require("../middilware/adminMiddleware");
router.post("/add",protect,admin,upload.single("image"),addvehicle);
router.get("/get",getvehicle);
router.get("/get/:id",getvehiclebyid);
router.delete("/delete/:id",protect,admin,deletevehiclebyid);
router.put("/update/:id",protect,admin,upload.single("image"),updatevehiclebyid);
router.get( "/search",searchAvailableVehicles);
module.exports=router;