const express=require("express");
const router=express.Router();
const protect=require("../middilware/authMiddleware");
const upload=require("../middilware/uploadMiddleware");
const {addvehicle,getvehicle,getvehiclebyid,deletevehiclebyid,updatevehiclebyid,searchAvailableVehicles}=require("../controllers/vehicleController");
router.post("/add",protect,upload.single("image"),addvehicle);
router.get("/get",protect,getvehicle);
router.get("/get/:id",protect,getvehiclebyid);
router.delete("/delete/:id",protect,deletevehiclebyid);
router.patch("/update/:id",protect,upload.single("image"),updatevehiclebyid);
router.get( "/search",searchAvailableVehicles);
module.exports=router;